services:
  agile-digest-app-ami:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: /api
        BACKEND_API_URL: http://agile-digest-api-standalone:3001
        NEXT_PUBLIC_API_TIMEOUT: "30000"
        NEXT_PUBLIC_LOG_API_REQUESTS: "true"

    image: agile-digest:latest
    container_name: agile-digest-didyeey

    env_file:
      - .env.staging

    environment:
      NEXT_PUBLIC_API_URL: /api
      BACKEND_API_URL: http://agile-digest-api-standalone:3001
      NEXT_PUBLIC_API_TIMEOUT: "30000"
      NEXT_PUBLIC_LOG_API_REQUESTS: "true"
      HOSTNAME: 0.0.0.0

    restart: always

    ports:
      - "3000:3000"

    networks:
      - agile-digest-network

networks:
  agile-digest-network:
    external: true